name: y_player
description: "YPlayer is a Flutter package that provides an easy-to-use YouTube video player widget"
version: 1.1.1
repository: https://github.com/ijashuzain/y_player

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_explode_dart: ^2.2.3
  video_player: ^2.9.1
  chewie: ^1.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
